# Generated by Django 4.0.5 on 2022-07-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cancelappointmen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cancelappointmen',
            new_name='cancelappointment',
        ),
    ]
